### PR TITLE
Fix for Enable and document running with TLS 

### PR DESCRIPTION
**Pull request by gagandeepp**
https://github.com/jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards/issues/62

### CODE REVIEW

**Comment by gagandeepp** [comment]
@jeroenheijmans Can you please give this a look?

**Comment by gagandeepp** [comment]
@jeroenheijmans Can you please have a look on this?

**Comment by jeroenheijmans** [comment]
Thanks for the PR!

I've been absolutely swamped at work this week, and will be for the next two days most likely as well. So I might not get to thinking about this PR some more.

The PR itself does seem to fit the bare minimal requirements I thought of initially in #62. I'd prefer to test it locally on both Windows and Linux before merging though.

Did you by any chance think about and/or try stuff with the e2e tests? And what would you think about making running with TLS the default? Or would that block many users? I'd love to make the world a bit more secure by default, but don't want to alienate folks if it creates hurdles...

**Comment by gagandeepp** [comment]
> Thanks for the PR!
> 
> I've been absolutely swamped at work this week, and will be for the next two days most likely as well. So I might not get to thinking about this PR some more.
> 
> The PR itself does seem to fit the bare minimal requirements I thought of initially in #62. I'd prefer to test it locally on both Windows and Linux before merging though.
> 
> Did you by any chance think about and/or try stuff with the e2e tests? And what would you think about making running with TLS the default? Or would that block many users? I'd love to make the world a bit more secure by default, but don't want to alienate folks if it creates hurdles...

Hi @jeroenheijmans  I have tested this on windows and macos ,it's working fine. I didnt think about e2e test but for making the TLS default,we need to add steps to generate the certificate and place it in the folder as described in the article.

https://medium.com/@rubenvermeulen/running-angular-cli-over-https-with-a-trusted-certificate-4a0d5f92747a

I know you are super busy but if it is possible can you add a hacktoberfest-accepted tag to this PR that will be great.

**Comment by jeroenheijmans** [comment]
> if it is possible can you add a hacktoberfest-accepted tag to this PR that will be great.

Fair enough! I've applied the label. You're good to go. If you want you can leave this PR sit for a while, when I have time I might check it out locally and maybe add some stuff to it, and then merge.

Thx for the help!

**Pull request merged**
